import { StyleSheet } from "react-native";

export const themeStyles = StyleSheet.create({
  container: {
    paddingTop: 30,
    alignItems: "center",
    backgroundColor: "#18191a",
    minHeight: "100%",
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#18191a",
  },
  title: {
    color: "#c2b280",
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 12,
    textAlign: "center",
    fontFamily: "serif",
    letterSpacing: 1,
    textShadowColor: "#222",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  clueTitle: {
    fontWeight: "bold",
    fontSize: 22,
    color: "#bfa76a",
    marginBottom: 10,
    marginTop: 10,
    fontFamily: "serif",
    letterSpacing: 0.5,
  },
  clueDesc: {
    fontSize: 17,
    color: "#e0e0d6",
    marginBottom: 16,
    textAlign: "center",
    fontStyle: "italic",
    lineHeight: 26,
    backgroundColor: "rgba(40,40,36,0.7)",
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#2d2d2d",
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  puzzleName: {
    fontWeight: "bold",
    fontSize: 18,
    color: "#bfa76a",
    marginBottom: 6,
    marginTop: 10,
    fontFamily: "serif",
    letterSpacing: 0.5,
  },
  puzzleDesc: {
    fontSize: 16,
    color: "#d6d6c2",
    marginBottom: 14,
    textAlign: "center",
    fontStyle: "italic",
    lineHeight: 24,
    backgroundColor: "rgba(40,40,36,0.6)",
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#232323",
  },
  button: {
    backgroundColor: "#bfa76a",
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 14,
    marginBottom: 28,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 2,
  },
  buttonText: {
    color: "#232323",
    fontWeight: "bold",
    fontSize: 19,
    letterSpacing: 0.5,
    fontFamily: "serif",
  },
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(24,25,26,0.92)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#232323",
    borderRadius: 22,
    padding: 30,
    width: "88%",
    alignItems: "center",
    position: "relative",
    borderWidth: 1,
    borderColor: "#bfa76a",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: "#bfa76a",
    borderRadius: 10,
    padding: 12,
    width: "100%",
    marginBottom: 12,
    fontSize: 17,
    backgroundColor: "#22221f",
    color: "#e0e0d6",
    fontFamily: "serif",
  },
  error: {
    color: "#b94a48",
    marginBottom: 10,
    fontSize: 15,
    fontStyle: "italic",
  },
  solveButton: {
    backgroundColor: "#232323",
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    marginBottom: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#bfa76a",
  },
  solveButtonText: {
    color: "#bfa76a",
    fontWeight: "bold",
    fontSize: 17,
    fontFamily: "serif",
  },
  closeButton: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 10,
    padding: 8,
  },

  questButton: {
    backgroundColor: "#bfa76a",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    marginBottom: 20,
    alignItems: "center",
    width: "90%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 2,
  },

  questDesc: {
    color: "#232323",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
    fontFamily: "serif",
  },
});
