import { StyleSheet } from "react-native";

export const themeStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 30,
    alignItems: "center",
    backgroundColor: "#10151b", // Djup mörkblå
    minHeight: "100%",
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#10151b",
  },
  title: {
    color: "#e0c97f", // Antik guld
    fontSize: 30,
    fontWeight: "700",
    marginBottom: 14,
    textAlign: "center",
    fontFamily: "serif",
    letterSpacing: 1,
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  clueTitle: {
    fontWeight: "bold",
    fontSize: 22,
    color: "#bfa76a",
    marginBottom: 10,
    marginTop: 10,
    fontFamily: "serif",
    letterSpacing: 0.5,
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  clueDesc: {
    fontSize: 17,
    color: "#e0e0d6",
    marginBottom: 16,
    textAlign: "center",
    fontStyle: "italic",
    lineHeight: 26,
    backgroundColor: "rgba(36, 32, 24, 0.7)", // Pergamentton
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#a67c52",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
  },
  puzzleName: {
    fontWeight: "bold",
    fontSize: 19,
    color: "#e0c97f",
    marginBottom: 8,
    marginTop: 10,
    fontFamily: "serif",
    letterSpacing: 0.5,
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  puzzleDesc: {
    fontSize: 16,
    color: "#e0e0d6",
    marginBottom: 14,
    textAlign: "center",
    fontStyle: "italic",
    lineHeight: 24,
    backgroundColor: "rgba(36, 32, 24, 0.6)",
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#a67c52",
  },
  button: {
    backgroundColor: "#bfa76a",
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 18,
    marginBottom: 28,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#a67c52",
  },
  buttonText: {
    color: "#232323",
    fontWeight: "bold",
    fontSize: 19,
    letterSpacing: 0.5,
    fontFamily: "serif",
  },
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(16,21,27,0.96)", // Djupare overlay
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#18191a",
    borderRadius: 24,
    padding: 32,
    width: "88%",
    alignItems: "center",
    position: "relative",
    borderWidth: 2,
    borderColor: "#bfa76a",
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: "#bfa76a",
    borderRadius: 10,
    padding: 12,
    width: "100%",
    marginBottom: 12,
    fontSize: 17,
    backgroundColor: "#23221f",
    color: "#e0e0d6",
    fontFamily: "serif",
  },
  error: {
    color: "#b94a48",
    marginBottom: 10,
    fontSize: 15,
    fontStyle: "italic",
  },
  solveButton: {
    backgroundColor: "#232323",
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 10,
    marginBottom: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#bfa76a",
  },
  solveButtonText: {
    color: "#bfa76a",
    fontWeight: "bold",
    fontSize: 17,
    fontFamily: "serif",
  },
  closeButton: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 10,
    padding: 8,
  },
  questButton: {
    backgroundColor: "#232323",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 16,
    marginBottom: 20,
    alignItems: "center",
    width: "90%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#bfa76a",
  },
  questDesc: {
    color: "#e0c97f",
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
    fontFamily: "serif",
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
});
