import { StyleSheet } from "react-native";
import { colors, radius } from "./tokens";

export const themeStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 30,
    alignItems: "center",
    backgroundColor: colors.bgPrimary,
    minHeight: "100%",
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.bgPrimary,
  },
  title: {
    color: colors.accentGoldSoft,
    fontSize: 30,
    fontWeight: "700",
    marginBottom: 14,
    textAlign: "center",
    fontFamily: "serif",
    letterSpacing: 1,
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  clueTitle: {
    fontWeight: "bold",
    fontSize: 22,
    color: colors.accentGold,
    marginBottom: 10,
    marginTop: 10,
    fontFamily: "serif",
    letterSpacing: 0.5,
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  clueDesc: {
    fontSize: 17,
    color: colors.textPrimary,
    marginBottom: 16,
    textAlign: "center",
    fontStyle: "italic",
    lineHeight: 26,
    backgroundColor: colors.parchmentStrong,
    padding: 14,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.accentBorder,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
  },
  puzzleName: {
    fontWeight: "bold",
    fontSize: 19,
    color: colors.accentGoldSoft,
    marginBottom: 8,
    marginTop: 10,
    fontFamily: "serif",
    letterSpacing: 0.5,
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  puzzleDesc: {
    fontSize: 16,
    color: colors.textPrimary,
    marginBottom: 14,
    textAlign: "center",
    fontStyle: "italic",
    lineHeight: 24,
    backgroundColor: colors.parchmentSoft,
    padding: 12,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  button: {
    backgroundColor: colors.accentGold,
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: radius.xl,
    marginBottom: 28,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: colors.accentBorder,
  },
  buttonText: {
    color: colors.textDark,
    fontWeight: "bold",
    fontSize: 19,
    letterSpacing: 0.5,
    fontFamily: "serif",
  },
  modalBg: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.bgSurface,
    borderRadius: radius.xxl,
    padding: 32,
    width: "88%",
    alignItems: "center",
    position: "relative",
    borderWidth: 2,
    borderColor: colors.accentGold,
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.accentGold,
    borderRadius: radius.sm,
    padding: 12,
    width: "100%",
    marginBottom: 12,
    fontSize: 17,
    backgroundColor: colors.bgElevated,
    color: colors.textPrimary,
    fontFamily: "serif",
  },
  error: {
    color: colors.danger,
    marginBottom: 10,
    fontSize: 15,
    fontStyle: "italic",
  },
  solveButton: {
    backgroundColor: colors.bgElevated,
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: radius.sm,
    marginBottom: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.accentGold,
  },
  solveButtonText: {
    color: colors.accentGold,
    fontWeight: "bold",
    fontSize: 17,
    fontFamily: "serif",
  },
  closeButton: {
    position: "absolute",
    top: 8,
    right: 8,
    zIndex: 10,
    padding: 8,
  },
  questButton: {
    backgroundColor: colors.bgElevated,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: radius.lg,
    marginBottom: 20,
    alignItems: "center",
    width: "90%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.accentGold,
  },
  questDesc: {
    color: colors.accentGoldSoft,
    fontSize: 16,
    textAlign: "center",
    fontWeight: "600",
    fontFamily: "serif",
    textShadowColor: "#000",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
});
